name: flutter_flux
version: 2.2.2
description: Flux library for uni-directional dataflow inspired by reflux and Facebook's flux architecture.
authors:
  - Workiva Client Platform Team <team-clientplatform@workiva.com>
  - Dustin Lessard <dustin.lessard@workiva.com>
  - Evan Weible <evan.weible@workiva.com>
  - Jay Udey <jay.udey@workiva.com>
  - Max Peterson <maxwell.peterson@workiva.com>
  - Trent Grover <trent.grover@workiva.com>
  - Jim Beveridge <jimbe@google.com>
homepage: https://github.com/Workiva/w_flux
dev_dependencies:
  coverage: "^0.7.2"
  dart_dev: "^1.0.0"
  dart_style: "^0.2.0"
  dartdoc: "^0.8.0"
  test: "^0.12.3+5"
