name: flutter_flux
version: 3.0.0
description: Flux library for uni-directional dataflow inspired by reflux and
  Facebook's flux architecture.
authors:
  - Workiva Client Platform Team <team-clientplatform@workiva.com>
  - Dustin Lessard <dustin.lessard@workiva.com>
  - Evan Weible <evan.weible@workiva.com>
  - Jay Udey <jay.udey@workiva.com>
  - Max Peterson <maxwell.peterson@workiva.com>
  - Trent Grover <trent.grover@workiva.com>
  - Jim Beveridge <jimbe@google.com>
homepage: https://github.com/jimbeveridge/flutter_flux
dependencies:
  flutter:
    path: ../flutter/packages/flutter
dev_dependencies:
  coverage: "^0.7.2"
  dart_dev: "^1.0.0"
  dart_style: "^0.2.0"
  dartdoc: "^0.8.0"
  rate_limit: ^0.1.0
  test: "^0.12.3+5"
