name: w_flux
version: 0.2.0
description: Flux library for uni-directional dataflow inspired by reflux and Facebook's flux architecture.
authors:
  - Workiva Client Platform Team <team-clientplatform@workiva.com>
  - Evan Weible <evan.weible@workiva.com>
  - Max Peterson <maxwell.peterson@workiva.com>
  - Trent Grover <trent.grover@workiva.com>
documentation:
homepage: https://github.com/Workiva/w_flux
dependencies:
  react: ">=0.5.0 <0.8.0"
dev_dependencies:
  test: 0.12.0-rc.0
  rate_limit: 0.1.0
